### ISSUE TITLE
Ruby interpolation not highlighted correctly

### ISSUE THREAD

**Issue by Mic92** [emacs-tree-sitter/tree-sitter-langs#27]
```
"#{1 + 'test'}"
```

is parsed as

```
program:
  string:
    interpolation:
      binary:
        integer:
        string:
          string_content:
```

However syntax highlight does not show it as an embedded coded also there is a query for interpolation in the file
